### ISSUE TITLE
<empty string> in console.log()

### ISSUE THREAD

**Issue by deiiviidas** [unplugin/unplugin-turbo-console#14]
### Describe the bug

![image](https://github.com/unplugin/unplugin-turbo-console/assets/25092057/c9d0b437-0f03-4179-b74c-bc02fd77cd9e)
![image](https://github.com/unplugin/unplugin-turbo-console/assets/25092057/3272533f-4c79-4d89-9722-7aa21095d997)
![image](https://github.com/unplugin/unplugin-turbo-console/assets/25092057/74ecfe8b-46ce-41f3-9652-e78e3d6f0365)

### Reproduction

just installed in vite/vue, "vue": "^3.3.4", "vite": "^5.0.0",

### System Info

```Shell
PS C:\Users\pc\Desktop\development\dbfz> npx envinfo --system --binaries --browsers
Need to install the following packages:
  envinfo@7.11.0
Ok to proceed? (y)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yuyinws** [comment]
It looks like a special behavior on FireFox, I'll fix it recently.
