### ISSUE TITLE
Colourized log with `%c` break the output

### ISSUE THREAD

**Issue by ManUtopiK** [unplugin/unplugin-turbo-console#15]
### Describe the bug

Making a complex log with color break the output of unplugin-turbo-console.
Here the log of Nuxt DevTools :
```
console.log(
  `✨ %cNuxt DevTools %c Press Shift + ${isMac ? 'Option' : 'Alt'} + D to open DevTools`,
  'color: black; border-radius: 3px 0 0 3px; padding: 2px 2px 1px 10px; background: #00DC82',
  'border-radius: 0 3px 3px 0; padding: 2px 10px 1px 2px; background: #00DC8220',
  '',
)
```
And the output:
![image](https://github.com/unplugin/unplugin-turbo-console/assets/188172/25052eb8-9ee0-466a-8e38-90935be272f2)

The [reproduction](https://stackblitz.com/edit/github-vdn75x?file=examples%2Fnuxt%2Fapp.vue) doesn't start correctly. After `pnpm install`, stop the terminal witch ctrl+c and start nuxt with `pnpm play:nuxt`.

### Reproduction

https://stackblitz.com/edit/github-vdn75x?file=examples%2Fnuxt%2Fapp.vue

### System Info

```Shell
System:
    OS: Linux 6.1 NixOS 23.11 (Tapir) 23.11 (Tapir)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 5.69 GB / 31.15 GB
    Container: Yes
    Shell: 5.9 - /run/current-system/sw/bin/zsh
  Binaries:
    Node: 20.9.0 - /run/current-system/sw/bin/node
    Yarn: 1.22.19 - ~/.local/share/npm/bin/yarn
    npm: 10.1.0 - /run/current-system/sw/bin/npm
    pnpm: 8.12.0 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chromium: 120.0.6099.109
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yuyinws** [comment]
It's not easy to handle this situation on one console expression. I think we  can use `console.group` to modify transform logic：

```js
console.group()

// generated by unpluign-turbo-console
console.log("%c🚀 main.ts:6%c🔦 http://localhost:3090/client#c3JjL21haW4udHM6Njox", "padding:2px 5px; border-radius:3px 0 0 3px;margin-bottom:5px;color: #fff; background: #3178C6", "background: #00DC8250;padding:2px 5px;border-radius:0 3px 3px 0;margin-bottom:5px");

// Original console.log
console.log('%cLog Message', 'color: orange');

console.groupEnd()
```

It will render like this:

![image](https://github.com/unplugin/unplugin-turbo-console/assets/38490578/12b0580e-5a82-4dc1-97ca-62b8d056e74a)

WDYT 👀 ?

**Comment by yuyinws** [comment]
Resolved on https://github.com/unplugin/unplugin-turbo-console/commit/086c2f3c94c69a569d0ab1ec579c2792e17949c1
