### ISSUE TITLE
Prefix/suffix support for console methods: warn, info, error.

### ISSUE THREAD

**Issue by andretchen0** [unplugin/unplugin-turbo-console#19]
### Clear and concise description of the problem

As a developer using Unplugin I want prefix/suffix support for:

* console.warn
* console.info
* console.error

... so that I can use e.g., `console.warn` with the same prefix/suffix as `console.log`.

I'm working on a library and prefixing/suffixing console messages provides users of the library a clear, consistent indication that my library is generating the message.

### Suggested solution

The [Rollup strip() plugin](https://github.com/rollup/plugins/blob/2a19079892f0bef53b557da965339cdef0a13a93/packages/strip/src/index.js#L41) optionally matches against any console methods and removes them. 

That might serve as a starting point.

### Additional context

Here's a [StackBlitz](https://stackblitz.com/edit/github-kcbiyc?file=src%2FApp.vue) showing only `console.log` getting prefix/suffix.

Console after clicking "Print Vue":

<img width="681" alt="Screenshot 2024-02-08 at 00 13 10" src="https://github.com/unplugin/unplugin-turbo-console/assets/20469369/d834c2c3-bca0-46c0-965d-292f3b133bb5">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by yuyinws** [comment]
This feature was released on https://github.com/unplugin/unplugin-turbo-console/releases/tag/v1.3.0

I'm glad to see that you want to integrate this plugin in [tres](https://github.com/Tresjs/tres). If you encounter any problems during this process, feel free to discuss with me.

**Comment by andretchen0** [comment]
@yuyinws

Thank you!
