### ISSUE TITLE
A very strange problem, I don't even know how to describe it

### ISSUE THREAD

**Issue by hooray** [unplugin/unplugin-turbo-console#22]
### Describe the bug

1. download the repo I provided, and choose the `example` branch
2. open `src/views/example/axios.vue` and add `console.log(res[0], '中文中文')` to:
```ts
function getInfo() {
  Promise.all([
    apiNews.list(),
    apiNews.list(),
  ]).then((res) => {
    console.log(res[0], '中文中文')  // <-- add here
    news.value = res[0].data.list.concat(
      res[1].data.list,
    )
  })
}
```
3. `pnpm run dev` and visit `http://localhost:5173/#/example/axios`
<img width="540" alt="image" src="https://github.com/unplugin/unplugin-turbo-console/assets/1574903/3876c983-dee7-4e5c-a269-ff7973d9d989">

The problem seems to be related to Chinese characters, but it doesn't report an error when I change it to something like the following, so I'm confused as to what exactly is causing the problem

- `console.log(res[0], '中文中')`
- `console.log('中文中文中文')`
- `console.log('中文中文', res[0])`

### Reproduction

https://github.com/hooray/fantastic-startkit/tree/example

### System Info

```Shell
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 64.61 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/Library/Caches/fnm_multishells/89869_1709865588279/bin/node
    Yarn: 1.22.21 - ~/Library/Caches/fnm_multishells/89869_1709865588279/bin/yarn
    npm: 10.2.4 - ~/Library/Caches/fnm_multishells/89869_1709865588279/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 122.0.6261.112
    Safari: 17.3.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yuyinws** [comment]
Thanks for your report.
This bug had been fixed on https://github.com/unplugin/unplugin-turbo-console/releases/tag/v1.4.1
