### ISSUE TITLE
Specify the ability of a single console not to use a plugin

### ISSUE THREAD

**Issue by hooray** [unplugin/unplugin-turbo-console#23]
### Clear and concise description of the problem

There are some consoles in the project that would prefer not to use the plugin's capabilities, as they may be presenting static information that is not intended for debugging.

### Suggested solution

I have no idea 😂

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by yuyinws** [comment]
Maybe we can implement this feature through comments(like eslint):

For example:
- One line disable
```js
// turbo-console-disable-next-line
console.log('foo')
```

```js
console.log('foo') // turbo-console-disable-line
```

- Full file disable
```js
/* turbo-console-disable */

console.log('foo')
console.log('bar')
```

WDYT👀?

**Comment by hooray** [comment]
I think it's great !
