### ISSUE TITLE
nx monorepo support

### ISSUE THREAD

**Issue by yumadilovtimur** [unplugin/unplugin-turbo-console#29]
### Clear and concise description of the problem

My nx monrepo has nextjs and vite react applications. The transition to the file does not work

### Suggested solution

Nx support (https://nx.dev)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by yuyinws** [comment]
I create a [nx monorepo](https://github.com/yuyinws/nx-monorepo) includes NextJS and React Vite projects. And it works well.

<img width="1103" alt="image" src="https://github.com/unplugin/unplugin-turbo-console/assets/38490578/307df05f-bf98-40af-b470-e8a86aa4fca8">

<img width="1385" alt="image" src="https://github.com/unplugin/unplugin-turbo-console/assets/38490578/19e5b26b-d60d-470f-94f3-45f0f4b3abc1">

You can update the `unplugin-turbo-console` to the latest version and try it again. If there are still problems, please provide a minimal reproduction.

**Comment by yumadilovtimur** [comment]
it helped: https://code .visualstudio.com/docs/setup/mac#_launching-from-the-command-line

**Comment by recallwei** [comment]
> It helped: https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line (MacOS) Perhaps you should add this to the README.
> 
> There was such an error: Could not open page.tsx in the editor. The editor process exited with an error: spawn code ENOENT.
> 
> Thanks!

Add this to the documentation or FAQ, otherwise, it will be misunderstood as a bug.

**Comment by yuyinws** [comment]
@recallwei 

It has been added before.
https://github.com/unplugin/unplugin-turbo-console#jump-to-editor-doest-work

**Comment by recallwei** [comment]
Oh, sorry. I forgot to read the readme because I was reading the documentation.
https://unplugin.unjs.io/showcase/unplugin-turbo-console.html
