### ISSUE TITLE
Optimization of LaunchEditor's console output

### ISSUE THREAD

**Issue by normal-coder** [unplugin/unplugin-turbo-console#30]
### Clear and concise description of the problem

The space for Console output is limited.

For example, the address `http://localhost:3070#c3JjL3N0b3JlL3VzZUF1dGhTdG9yZS50czozNzoyNQ==` output by LaunchEditor corresponds to the relative directory of the project `src/store/useAuthStore.ts:37:25` after being decoded from base64. 

As the complexity of the project directory increases, the length of the text will also increase, and it will not be elegant to use Console panel output space. Although the above address is already short enough, such URLs will wrap in a small window state, causing waste of Console output space. I hope this issue can be optimized.

### Suggested solution

In the LaunchEditor output, it might be possible to solve the problem by maintaining a temporary mapping relationship. By creating a mapping relationship for the files, the addresses of the various types of files are mapped, and only the plugin's own routing address is provided in the Console.

### Alternative

1. Maintain file mapping through plugins to shorten the LaunchEditor debug address, for example, keeping it at a length of 6 digits (or even allowing this length to be customized?)
2. Allow users to switch between using `file path` + `line number` for base64 encoding or having the plugin maintain file mapping to determine the output format of the LauchEditor URL through configuration.

### Additional context

No context screenshot required.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by yuyinws** [comment]
Thank you. This is indeed a problem that needs to be optimized. Maintaining a temporary route mapping relationship sounds good, I will try this solution recently.

**Comment by yuyinws** [comment]
This feature released on [v1.8.0 (release)](https://github.com/unplugin/unplugin-turbo-console/releases/tag/v1.8.0)
