### ISSUE TITLE
使用装饰器模式开发,报错: "decorators", "decorators-legacy".

### ISSUE THREAD

**Issue by pyt111** [unplugin/unplugin-turbo-console#34]
### Describe the bug

[plugin:unplugin-turbo-console] This experimental syntax requires enabling one of the following parser plugin(s): "decorators", "decorators-legacy". (18:0)
![image](https://github.com/unplugin/unplugin-turbo-console/assets/23203040/59573b6c-7877-492e-9dda-1c9ba6f4e7c7)

![image](https://github.com/unplugin/unplugin-turbo-console/assets/23203040/f826c5b9-c4e2-408f-b1a4-958d7c61ba9d)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-s1mfjm?file=src%2Fcomponents%2FHelloWorld.vue

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 31.55 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.7.0 - /usr/local/bin/npm
    pnpm: 9.3.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 126.0.6478.62
    Safari: 17.4.1
  npmPackages:
    @vitejs/plugin-vue: ^5.0.4 => 5.0.5 
    typescript: ^5.2.2 => 5.4.5 
    unplugin-turbo-console: ^1.8.6 => 1.8.6 
    vite: ^5.2.0 => 5.3.1 
    vue: ^3.4.21 => 3.4.29 
    vue-facing-decorator: ^3.0.4 => 3.0.4 
    vue-tsc: ^2.0.6 => 2.0.21
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yuyinws** [comment]
It seems a bug from `vue-facing-decorator`.
I get the same error when remove `unplugin-turbo-console`.

<img width="545" alt="image" src="https://github.com/unplugin/unplugin-turbo-console/assets/38490578/3ec36ee1-d068-49e1-ba39-78ed681517e1">
<img width="1388" alt="image" src="https://github.com/unplugin/unplugin-turbo-console/assets/38490578/532387e3-f6e3-4d67-b769-872c20fe297e">

**Comment by pyt111** [comment]
> It seems a bug from `vue-facing-decorator`. I get the same error when remove `unplugin-turbo-console`.
> 
> <img alt="image" width="545" src="https://private-user-images.githubusercontent.com/38490578/340942525-3ec36ee1-d068-49e1-ba39-78ed681517e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NzgzNTcsIm5iZiI6MTcxODc3ODA1NywicGF0aCI6Ii8zODQ5MDU3OC8zNDA5NDI1MjUtM2VjMzZlZTEtZDA2OC00OWUxLWJhMzktNzhlZDY4MTUxN2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA2MjA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4YjA2MzVkMDIzZGY1YTMwMmQxM2U4Yzc5ODEyY2YyNTcyNjRhODdhZWUyZDMwYzBkMzA1MGI0N2I2M2UzOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iM3mYeb0KuZ4LyEvsKAZmiOm3GdTrN3vrLxa8VkKhz4"> <img alt="image" width="1388" src="https://private-user-images.githubusercontent.com/38490578/340942553-532387e3-f6e3-4d67-b769-872c20fe297e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NzgzNTcsIm5iZiI6MTcxODc3ODA1NywicGF0aCI6Ii8zODQ5MDU3OC8zNDA5NDI1NTMtNTMyMzg3ZTMtZjZlMy00ZDY3LWI3NjktODcyYzIwZmUyOTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA2MjA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMjZkNmZkOWU0YzE5OTUwYzkzMWI4Nzk1YTNmY2QzYmRlMTA3ZjBjYjBlYWY5NjVlNTgyYWVmY2EzNTYyZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gSHB6BCkKILumRLP500RtCJZR3Bx726sJFmnaS1Kx0Q">

关掉 `unplugin-turbo-console`后，是`vue/compiler-sfc`报错了，这个案例中没有配置
看这个新的案例：
(https://stackblitz.com/~/github.com/pyt111/my-vue-test-decorators)

**Comment by yuyinws** [comment]
那就说明这个错误与unplugin-turbo-console无关，似乎应该提给vue-facing-decorator

**Comment by pyt111** [comment]
> 那就说明这个错误与unplugin-turbo-console无关，似乎应该提给vue-facing-decorator

卸载vue-facing-decorator 使用vue-class-component，同样会有问题。只要使用装饰器就会抛出错误
