### ISSUE TITLE
error on using package has `import ... from ... with {type: 'json'}`

### ISSUE THREAD

**Issue by naramdash** [unplugin/unplugin-turbo-console#35]
### Describe the bug

![image](https://github.com/unplugin/unplugin-turbo-console/assets/24370799/7216bd30-beac-4773-9af0-85c05880f96c)

If i use a package has [`import with {type: 'json'}`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#:~:text=Toggle%20history-,with%20%7Btype%3A%20%27json%27%7D,-123), turbo-console raises an error related to babel parser.

Scripts `vite build`, and `vite dev` work well without turbo-console.

You can reproduce this error with a github repo link on reproduction.

### Reproduction

https://github.com/naramdash/test-turbo-import-with-json

### System Info

```Shell
System:
    OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (22) x64 Intel(R) Core(TM) Ultra 9 185H
    Memory: 18.13 GB / 30.88 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.14.0 - ~/.volta/tools/image/node/20.14.0/bin/node
    Yarn: 4.2.2 - ~/.volta/tools/image/yarn/4.2.2/bin/yarn
    npm: 10.7.0 - ~/.volta/tools/image/node/20.14.0/bin/npm
    pnpm: 9.1.3 - ~/.volta/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.61
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yuyinws** [comment]
Thanks for your report. It should been fixed on https://github.com/unplugin/unplugin-turbo-console/releases/tag/v1.8.7

**Comment by yuyinws** [comment]
Hi, just a notice. On the new version([v1.8.8](https://github.com/unplugin/unplugin-turbo-console/releases/tag/v1.8.8)), we expose babel parser plugins to the options. 
So you need config `importAttributes` manually like this:

```ts
export default defineConfig({
  plugins: [
    TurboConsole({
      babelParserPlugins: [
        'importAttributes',
      ]
    }),
  ]
})

```

**Comment by naramdash** [comment]
Thank you @yuyinws , It works good!
