### ISSUE TITLE
Redirect server logs to browser console during development

### ISSUE THREAD

**Issue by unlocomqx** [unplugin/unplugin-turbo-console#36]
### Clear and concise description of the problem

I would like to view server logs in the browser console during development. The browser console is more convenient for inspecting js objects for example. 

### Suggested solution

The plugin could send the logs via the socket (Just guessing as I don't know the internals)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by yuyinws** [comment]
Nuxt has a [similar feature](https://github.com/nuxt/nuxt/pull/25936). I will try to integrate it on this plugin.

**Comment by unlocomqx** [comment]
That's where I got the idea. I saw it on Twitter I think. It would be cool to have it in other frameworks. Thank you for your neat work!

**Comment by yuyinws** [comment]
This feature had release on v1.9.0.
You can refer [docs](https://github.com/unplugin/unplugin-turbo-console#pass-server-logs-to-client) for usage detail.

**Comment by unlocomqx** [comment]
Thank you for implementing this feature, it's so useful!

I will try it and give you my feedback

Thank you

**Comment by unlocomqx** [comment]
Hi
I tried it with SSR (using sveltekit)
The websocket is initialized by the client, so the server logs before the client init are not reported. 
I suggested dumping the server logs to the client using a script tag when the socket is not yet init'ed

Thank you

**Comment by yuyinws** [comment]
Could you provide a minimal reproduction for you usecase?

**Comment by unlocomqx** [comment]
Here's the simplest [repro](https://github.com/unlocomqx/unplugin-turbo-console-issue-36)

Thank you

**Comment by yuyinws** [comment]
I try to transform the `initWebsocket` to IIFE and use a script tag to load it.

```html
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" href="%sveltekit.assets%/favicon.png" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		%sveltekit.head%
	</head>
	<script src="/@id/__x00__~console"></script>
	<body data-sveltekit-preload-data="hover">
		<div style="display: contents">%sveltekit.body%</div>
	</body>
</html>

```

Unfortunately it still have the same question. 

What do you mean `dumping the server logs to the client using a script tag when the socket is not yet init'ed` ?

**Comment by unlocomqx** [comment]
I meant including the logs in the html directly when the websocket is still not initialized. 

Example:

tConsole.log('Hello')

injects a script like this

<script>
window.console.log('Server Log: Hello')
</script>

Otherwise when the page is loading, there won't be a socket to receive the message

**Comment by yuyinws** [comment]
[tConsole](https://github.com/unplugin/unplugin-turbo-console/blob/main/src/helper.ts#L15) is a runtime function and called on the server side. 

I'm not familiar with Sveltekit, is there any way to inject a <script> tag directly on the server side?

**Comment by unlocomqx** [comment]
Okay, I thought it's transformed at compile time.

You can close the issue as the remaining problem is relatively trivial

Thank you very much
