### ISSUE TITLE
Unsupported syntax "optionalChainingAssign"

### ISSUE THREAD

**Issue by itmanyong** [unplugin/unplugin-turbo-console#37]
### Describe the bug

不支持链式判断的语法，如下图所示
![image](https://github.com/unplugin/unplugin-turbo-console/assets/53500371/df551bbd-c4b2-443f-8b9b-d9822be926da)

### Reproduction

null

### System Info

```Shell
win10 x64
vite5+
vue3.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yuyinws** [comment]
你是不是安装了`vite-plugin-babel`插件来支持这个语法？
在vite配置中，把TurboConsole()放到babel()的后面再试试

```js
import vue from '@vitejs/plugin-vue'
import TurboConsole from 'unplugin-turbo-console/vite'
import babel from 'vite-plugin-babel';

export default defineConfig({
plugins: [
    vue(),
    babel(),
    TurboConsole(), // 放在babel后面
  ],
})
```

**Comment by itmanyong** [comment]
> 你是不是安装了`vite-plugin-babel`插件来支持这个语法？ 在vite配置中，把TurboConsole()放到babel()的后面再试试
> 
> ```js
> import vue from '@vitejs/plugin-vue'
> import TurboConsole from 'unplugin-turbo-console/vite'
> import babel from 'vite-plugin-babel';
> 
> export default defineConfig({
> plugins: [
>     vue(),
>     babel(),
>     TurboConsole(), // 放在babel后面
>   ],
> })
> ```
并没有，没有安装任何babel之类的扩展插件，就是基于vite的，vite默认是支持这类语法的，很奇怪的是我其他地方写这种语法没事，就这个地方用了就显示这个错误

**Comment by yuyinws** [comment]
@itmanyong 

把unplugin-turbo-console禁用了，还会不会有这个错误

**Comment by yuyinws** [comment]
请升级到最新的beta版本(1.8.8-beta.1)，然后在 vite 配置文件进行以下配置：再看看会不会报错

```js
export default defineConfig({
  plugins: [
    vue(),
    TurboConsole({
      babelParserPlugins: [
        ['optionalChainingAssign', {version: '2023-07'}]
      ]
    }),
  ],
})
```

**Comment by itmanyong** [comment]
> 在最新的beta版本(1.8.8-beta.1)中把插件内部的babel插件选项暴露出来了,可以升级到最新的beta版本再尝试一下。 Vite 配置文件进行以下配置：
> 
> ```js
> export default defineConfig({
>   plugins: [
>     vue(),
>     TurboConsole({
>       babelParserPlugins: [
>         ['optionalChainingAssign', {version: '2023-07'}]
>       ]
>     }),
>   ],
> })
> ```

更新到beta后设置了这个配置后就没有报错问题了，应该就是内部这个配置导致的问题

**Comment by yuyinws** [comment]
已在[v1.8.8](https://github.com/unplugin/unplugin-turbo-console/releases/tag/v1.8.8) 发布.
