### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined 

### ISSUE THREAD

**Issue by long36708** [unplugin/unplugin-turbo-console#53]
### Describe the bug

从1.10.4升级到版本 1.11.0 ，启动报错
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in F:\learn_vue2_console\node_modules\unplugin-turbo-console\node_modules\estree-walker\package.json

### Reproduction

https://github.com/long36708/vue-cli-project

### System Info

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
    Memory: 30.59 GB / 47.33 GB
  Binaries:
    Node: 18.20.5 - D:\dev\Volta\tools\image\node\18.20.5\node.EXE
    Yarn: 1.22.19 - D:\dev\Volta\tools\image\yarn\1.22.19\bin\yarn.CMD
    npm: 10.8.2 - D:\dev\Volta\tools\image\node\18.20.5\npm.CMD
    pnpm: 8.15.9 - D:\dev\Volta\tools\image\pnpm\8.15.9\bin\pnpm.CMD
  Browsers:
    Edge: Chromium (125.0.2535.67)
    Internet Explorer: 11.0.26100.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yuyinws** [comment]
Thanks for your report. It's a upstream issue from [estree-walker#26](https://github.com/Rich-Harris/estree-walker/issues/26). 
And it had been fixed on [v1.11.1](https://github.com/unplugin/unplugin-turbo-console/releases/tag/v1.11.1).
